insert into nationality (id, name) values (default, 'Belarusian');
insert into nationality (id, name) values (default, 'Russian');
insert into nationality (id, name) values (default, 'French');
insert into nationality (id, name) values (default, 'Ukrainian');
insert into nationality (id, name) values (default, 'Turkish');
insert into nationality (id, name) values (default, 'Polish');
insert into nationality (id, name) values (default, 'German');
insert into nationality (id, name) values (default, 'Latvian');
insert into nationality (id, name) values (default, 'Austrian')