-- insert into nationality (id, name) values (default, 'Belarusian');
-- insert into nationality (id, name) values (default, 'Russian');
-- insert into nationality (id, name) values (default, 'French');
-- insert into nationality (id, name) values (default, 'Ukrainian');
-- insert into nationality (id, name) values (default, 'Turkish');
-- insert into nationality (id, name) values (default, 'Polish');
-- insert into nationality (id, name) values (default, 'German');
-- insert into nationality (id, name) values (default, 'Latvian');
-- insert into nationality (id, name) values (default, 'Austrian');
--
-- insert into profession (id, name) values (default, 'Architects');
-- insert into profession (id, name) values (default, 'Chemical Engineers');
-- insert into profession (id, name) values (default, 'Mechanical Engineers');
-- insert into profession (id, name) values (default, 'Electronic Engineers');
-- insert into profession (id, name) values (default, 'Librarians');
-- insert into profession (id, name) values (default, 'Economists');
-- insert into profession (id, name) values (default, 'Sociologists');
-- insert into profession (id, name) values (default, 'Urban Planners');
-- insert into profession (id, name) values (default, 'Physicians');
-- insert into profession (id, name) values (default, 'Dentists');
-- insert into profession (id, name) values (default, 'Veterinarians');
-- insert into profession (id, name) values (default, 'Podiatrists');
-- insert into profession (id, name) values (default, 'Optometrists');
--
-- insert into language (id, name) values (default, 'Belarusian');
-- insert into language (id, name) values (default, 'Russian');
-- insert into language (id, name) values (default, 'German');
-- insert into language (id, name) values (default, 'Italian');
-- insert into language (id, name) values (default, 'Latvian');
-- insert into language (id, name) values (default, 'Polish');
-- insert into language (id, name) values (default, 'Spanish');
-- insert into language (id, name) values (default, 'Swedish');
-- insert into language (id, name) values (default, 'Turkmen');
-- insert into language (id, name) values (default, 'Chinese');
-- insert into language (id, name) values (default, 'French');
-- insert into language (id, name) values (default, 'Greek');
-- insert into language (id, name) values (default, 'Japanese');
-- insert into language (id, name) values (default, 'English');

insert into administrator (id, firstname, lastname, password, email, role) values (default, 'Mikalai', 'Luksha', 'qwert', 'lucsha@gmail.com','admin')
